version: "3.7"

services:
    dev-container:
        image: registry.gitlab.com/musement/golang/docker:1.15-dev
        container_name: pricing-service-dev-container
        command: sleep infinity
        volumes:
            - /tmp:/tmp
            - ${PWD}:${PWD}
            - /var/run/docker.sock:/var/run/docker.sock:rw
        privileged: true
        depends_on:
            - dynamo

    dynamo:
        command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
        image: amazon/dynamodb-local:latest
        ports:
            - "8000:8000"
        volumes:
            - "./docker/dynamodb:/home/dynamodblocal/data"
        working_dir: /home/dynamodblocal
